PARTEA 1

1. SELECT FIRST_NAME AS "Prenume", LAST_NAME AS "Nume"
FROM employees

2. SELECT DISTINCT DEPARTMENT_ID
FROM employees

3. SELECT * FROM employees ORDER BY FIRST_NAME DESC

4. SELECT FIRST_NAME, LAST_NAME, SALARY, 16*SALARY/100 AS "TAX" FROM employees

5. SELECT EMPLOYEE_ID, FIRST_NAME,LAST_NAME, SALARY FROM employees ORDER BY SALARY ASC

6. SELECT SUM(SALARY) AS "TOTAL_PAYMENTS" FROM employees

7. SELECT MIN(SALARY) AS "MIN_SALARY", MAX(SALARY) AS "MAX_SALARY" FROM employees

8. SELECT AVG(SALARY) AS "AVG_SALARY", COUNT(*)/COUNT(*) AS "AVG_PERSONNEL" FROM employees

9. SELECT COUNT(*) AS "NR_OF_EMPLOYEES" FROM employees

10. SELECT COUNT(DISTINCT JOB_ID) AS "NR_OF_JOBS" FROM jobs

11. SELECT MAX_SALARY FROM jobs WHERE JOB_ID = "IT_PROG"

12. SELECT AVG(SALARY) AS "AVG_SALARY", COUNT(*) AS "NR_OF_EMPLOYEES" FROM employees WHERE DEPARTMENT_ID = 90

13. SELECT MAX(SALARY) AS "MAX_SALARY", MIN(SALARY) AS "MIN_SALARY", SUM(SALARY) AS "SUM_SALARY", AVG(SALARY) AS "AVG_SALARY" FROM employees

14. SELECT AVG(SALARY) AS "AVG_PER_DEPARTMENT", DEPARTMENT_ID FROM employees GROUP BY DEPARTMENT_ID

15. SELECT JOB_TITLE, (MAX_SALARY+MIN_SALARY)/2 AS "AVG_SALARY" FROM jobs GROUP BY JOB_ID

16. SELECT DEPARTMENT_ID, SUM(SALARY)/COUNT(DISTINCT EMPLOYEE_ID) as "EMPLOYEE_ID"
FROM employees
GROUP BY DEPARTMENT_ID
HAVING COUNT(DISTINCT EMPLOYEE_ID) > 10

PARTEA 2

1. SELECT DEPARTMENT_NAME, locations.LOCATION_ID, locations.STREET_ADDRESS, locations.POSTAL_CODE, locations.CITY, locations.STATE_PROVINCE, countries.COUNTRY_NAME
FROM departments
INNER JOIN locations ON locations.LOCATION_ID = departments.LOCATION_ID
INNER JOIN countries ON countries.COUNTRY_ID = locations.COUNTRY_ID

2. SELECT FIRST_NAME, LAST_NAME, departments.DEPARTMENT_ID, departments.DEPARTMENT_NAME
FROM employees
INNER JOIN departments ON departments.DEPARTMENT_ID = employees.DEPARTMENT_ID

3. SELECT FIRST_NAME, LAST_NAME, JOB_ID, departments.DEPARTMENT_ID, departments.DEPARTMENT_NAME
FROM employees
INNER JOIN departments ON departments.DEPARTMENT_ID = employees.DEPARTMENT_ID
INNER JOIN locations ON locations.LOCATION_ID = departments.LOCATION_ID
WHERE locations.CITY = "London"

4. SELECT EMPLOYEE_ID, LAST_NAME, MANAGER_ID, LAST_NAME
FROM employees

5.  SELECT FIRST_NAME, LAST_NAME, HIRE_DATE
FROM employees
WHERE HIRE_DATE > (SELECT HIRE_DATE FROM employees WHERE LAST_NAME = "Jones")

6. SELECT DEPARTMENT_NAME, COUNT(employees.EMPLOYEE_ID) AS "NR_OF_EMPLOYEES"
FROM departments
INNER JOIN employees ON employees.DEPARTMENT_ID = departments.DEPARTMENT_ID
GROUP BY DEPARTMENT_NAME

7. SELECT employees.EMPLOYEE_ID, jobs.JOB_ID, DATEDIFF(job_history.END_DATE , job_history.START_DATE) AS "TIME_WORKED"
FROM job_history
INNER JOIN jobs ON jobs.JOB_ID = job_history.JOB_ID
INNER JOIN employees ON employees.EMPLOYEE_ID = job_history.EMPLOYEE_ID

8. SELECT departments.DEPARTMENT_ID, departments.DEPARTMENT_NAME, employees.FIRST_NAME
FROM departments
INNER JOIN employees ON employees.EMPLOYEE_ID = departments.MANAGER_ID

9.  SELECT departments.DEPARTMENT_NAME, employees.FIRST_NAME, employees.LAST_NAME, locations.CITY
FROM departments
INNER JOIN locations ON departments.LOCATION_ID = locations.LOCATION_ID
INNER JOIN employees ON departments.MANAGER_ID = employees.EMPLOYEE_ID














